name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: problem1.py
      id: problem1-py
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: problem1.py
        setup-command: pip install pytest
        command: pytest
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PROBLEM1-PY_RESULTS: "${{steps.problem1-py.outputs.result}}"
      with:
        runners: problem1-py
